data_dir = "D:/ai-github/cc-connect/mutilbot/instance-mutilbot4/data"
language = "zh"

[[projects]]
  name = "instance-mutilbot4-project-xingzou"
  [projects.agent]
    type = "codex"
    [projects.agent.options]
      mode = "yolo"
      provider = "rightcode"
      work_dir = "D:/ai-github/cc-connect/mutilbot/instance-mutilbot4"

    [[projects.agent.providers]]
      name = "rightcode"
      api_key = "sk-ed3199aad41c43bebccc14340ebd7741"
      base_url = "https://right.codes/codex/v1"
      model = "gpt-5.2"

    [[projects.agent.providers]]
      name = "codez"
      api_key = "sk-BXPhBqt16uaEgGElLx9IpOJmfLRSwYtBQ7NjHlbMaCEBKy88"
      base_url = "https://api.zwenooo.link/v1"
      model = "gpt-5.2"

  [[projects.platforms]]
    type = "feishu"
    [projects.platforms.options]
      allow_from = "*"
      app_id = "cli_a9324e0f6e7bdceb"
      app_secret = "vxfBbBWipgQcwpuvfmoGOc48br1vG73F"
      reaction_emoji = "OnIt"

[log]
  level = "info"

[speech]
  enabled = false
  provider = ""
  language = ""
  [speech.openai]
    api_key = ""
    base_url = ""
    model = ""
  [speech.groq]
    api_key = ""
    model = ""

[display]
  thinking_max_len = 300
  tool_max_len = 500
